version: '3'

services:
  midas-news-parser:
    container_name: midas-news-parser
    image: midas/news-parser:0.1.0
    build: .
    networks:
      - midas
    environment:
      - NEWS_KEYWORDS=petrobras
      - DEPLOY=local
      - BUCKET=dev-midas-news-scoring

  minio:
    container_name: minio
    image: quay.io/minio/minio
    command: server /data --console-address ":9001"
    networks:
      - midas
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      - MINIO_ROOT_USER=miniodev
      - MINIO_ROOT_PASSWORD=miniodev

networks:
  midas:
    name: midas
